### ISSUE TITLE
search for "note" returns a syntax error?

### ISSUE THREAD

**Issue by Manoj321** [femto-dev/femto#10]
```
# femto_search --matches index "note" -v
syntax error
Could not parse pattern note
```

Looks like a bug.
May be its getting confused for "not" ?

**Comment by Manoj321** [comment]
This is true for "and" as well.
Search for "andblah" returns syntax error.
Other boolean keywords seems to be fine.

**Comment by mppf** [comment]
You can do a workaround with
    femto_search --matches index '"note"' -v
I'll look into it.

**Comment by mppf** [comment]
The problem only comes up if the boolean keyword starts the pattern.
