### ISSUE TITLE
Indexing a file: What is the worst case memory consumption?

### ISSUE THREAD

**Issue by Manoj321** [femto-dev/femto#12]
I was trying to index a 5GB file and looks like femto is using all the free memory( about 57GB! )
Amount of memory required is not the problem. 
Knowing memory requirements before hand( depending on input file size? ) will help.
Does changing  block_size & chunk_size improve speed?

**Comment by mppf** [comment]
Block size and chunk size affect compression and search speed. Indexing speed is dominated by suffix array construction.

The suffix array construction can use a main memory or external memory algorithm. The implementation started out tuned to use up to 16GB of memory. By default, the implementation tries to pick between in memory and external memory indexing based upon the available memory and the size of the input (or subproblem during recursion).

The indexer usage prints out some useful options:

     --sort-memory -- amount of memory to use when sorting, in MB\n");
     --inmem or --no-inmem -- use (don't use) in memory suffix sorter

Especially the external memory one uses mmap a lot and so virtual memory used will be much bigger than actual RAM used. The external memory indexer will use approx 42n disk space in the worst case to index n bytes of input.

The main memory implementation uses 5-6n memory if I recall correctly.

I welcome documentation update PRs with this information. Or bug fixes. It would not be surprising if there is a bug in the code estimating memory usage.

**Comment by mppf** [comment]
Have you tried specifying --sort-memory ?
