### ISSUE TITLE
OpenMPI build

### ISSUE THREAD

**Issue by paulalmaev** [femto-dev/femto#13]
I don't know if anyone experienced issues with building openmpi for this project. If you follow the steps in the readme document:

```
root@ubuntu:~/source/openmpi-1.4.2# ./autogen.sh
root@ubuntu:~/source/openmpi-1.4.2# ./configure --prefix=/opt/openmpi1.4.2 --enable-mpirun-prefix-by-default --enable-mpi-threads --with-threads 
```
It shows a problem that is most likely caused by the newer libtool:
> aclocal-1.15: error: ../../config/mca_m4_config_include.m4:8: file 'opal/mca/backtrace/configure.m4' does not exist

I tested with openmpi (1.8.8) which builds fine. Note, the flag **--enable-mpi-threads** has been changed to **--enable-mpi-thread-multiple**

```
  --enable-mpi-thread-multiple
                          Enable MPI_THREAD_MULTIPLE support (default:
                          disabled)
```
The commands should be:

```
./configure --prefix=/opt/openmpi1.8.8 --enable-mpirun-prefix-by-default --enable-mpi-thread-multiple --with-threads
make
make install
export PATH=$PATH:/opt/openmpi1.8.8/bin
export LD_LIBRARY_PATH=/opt/openmpi1.8.8/lib
```

**Comment by mppf** [comment]
hi @paulalmaev, go ahead and make a PR to fix the documentation, if you would. thanks
