### ISSUE TITLE
Does this support multiline search?

### ISSUE THREAD

**Issue by Manoj321** [femto-dev/femto#7]
before trying to install, I just wanted to know if this supports multiline search?
I know that RE2 supports this. 
Ex:
```
"hello



world"
```
regex pattern "hello.{1,10}world"
Are there any restrictions due to suffix layer on top of this?

**Comment by mppf** [comment]
Yes, it supports multi-line search.  See
 https://github.com/femto-dev/femto/blob/master/src/main/QUERY_FORMAT.txt

**Comment by Manoj321** [comment]
great thanks!
