### ISSUE TITLE
make fails with "posix.flex.c: No such file or directory" error

### ISSUE THREAD

**Issue by Manoj321** [femto-dev/femto#8]
I have installed all the required deps . Is there anything missing here?
```
make[4]: Entering directory '/home/femto/src/main'
/bin/bash ../../ylwrap posix.flex.l .c posix.flex.c -- /bin/bash /home/femto/missing flex  
lex.yyposix.flex.c is unchanged
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -I./../utils   -std=gnu99 -Wall -m64 -D_64_BIT -fopenmp -D_XOPEN_SOURCE=600 -O4 -fomit-frame-pointer -DEXTRA_CHECKS=0 -march=native -mtune=native -MT posix.flex.lo -MD -MP -MF .deps/posix.flex.Tpo -c -o posix.flex.lo posix.flex.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I./../utils -std=gnu99 -Wall -m64 -D_64_BIT -fopenmp -D_XOPEN_SOURCE=600 -O4 -fomit-frame-pointer -DEXTRA_CHECKS=0 -march=native -mtune=native -MT posix.flex.lo -MD -MP -MF .deps/posix.flex.Tpo -c posix.flex.c  -fPIC -DPIC -o .libs/posix.flex.o
gcc: error: posix.flex.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
```

**Comment by mppf** [comment]
Can you tell me what version OS you are using?

**Comment by Manoj321** [comment]
I'm using ubuntu kernel version 4.0.5. 64 bit system.
Here is the apt-cache policy <package> o/p:
```
flex:
  Version table:
     2.5.39-8 0
bison:
  Version table:
     2:3.0.2.dfsg-2 0
```

**Comment by mppf** [comment]
Have you tried using a release tarball (from the releases tab above)?
Have you tried building with cmake ? e.g.
  mkdir build
  cmake ..
  make

I will try to reproduce with an Ubuntu 15 and 16 at some point, but that might take me some time.

**Comment by Manoj321** [comment]
Haven't tried using release tar ball. I'll give it a try.

Thanks.

**Comment by Manoj321** [comment]
cmake worked flawlessly!

**Comment by mppf** [comment]
vagrant init ubuntu/wily64
    # (configured VM for 4GB of memory instead of 512MB)
    vagrant up
    vagrant ssh
    sudo apt-get install git libssl-dev g++ flex bison automake autoconf libtool
    git clone https://github.com/femto-dev/femto.git
    cd femto
    sh autogen.sh
    ./configure
    make
    cd src/test
    make check

worked for me.
