### ISSUE TITLE
Multiline Queries are going exponential?

### ISSUE THREAD

**Issue by Manoj321** [femto-dev/femto#9]
Is the following behavior expected?
The index file was generated using a 3MB text file.
As the number of characters in between two words increases the time is increasing exponentially!
I thought RE2 scales linearly. 

```
#ls -lh index.3M 
-rw-r--r-- 1 root root 952K Feb 17 00:57 index.3M

#time ./femto_search index.3M  "world.{1,10}hello"
real    0m0.138s
user    0m0.135s
sys     0m0.001s

#time ./femto_search index.3M  "world.{1,20}hello"
real    0m0.639s
user    0m0.634s
sys     0m0.001s

#time ./femto_search index.3M  "world.{1,40}hello"
real    0m4.319s
user    0m4.300s
sys     0m0.001s

#time ./femto_search index.3M  "world.{1,80}hello"
real    0m35.405s
user    0m35.239s
sys     0m0.015s

#time ./femto_search index.3M  "world.{1,160}hello"
real    5m53.839s
user    5m51.885s
sys     0m0.102s

```

**Comment by mppf** [comment]
This behavior is expected. While the index can speed up many regular expression queries, it is optimized for those with a small number of actual completions in the data. See the paper in doc/ for more details.
Running femto_search does not use RE2 in order to do the regular expression search.

For the kind of search you are doing, you might find it faster to use THEN which supports a distance argument.

**Comment by mppf** [comment]
Also note that one of the interesting capabilities of FEMTO is that you can ask it to print out the ways that such a regexp completes. That is what --matches. When doing a regexp query, the matches are computed before any results are found.

**Comment by Manoj321** [comment]
yes, THEN is definitely faster than {m,n}. Most of the queries complete under 0.5 sec!
I have few doubts:
1. I see that FEMTO depends on RE2 - How is RE2 used here?

2.Following queries seems to be slow. Any alternatives?
```
hello\ ([^ ]+)
hello.{100}
hello\ \'[^\']+

```

**Comment by Manoj321** [comment]
yes, THEN is definitely faster than {m,n}. Most of the queries complete under 0.5 sec!
I have few doubts:
1. I see that FEMTO depends on RE2 - How is RE2 used here?

2.Following queries seems to be slow. Any alternatives?
```
hello\ ([^ ]+)
hello.{100}
hello\ \'[^\']+

```

**Comment by mppf** [comment]
1. FEMTO uses RE2 to implement the tool femto_scan, which uses the same query format as FEMTO but does it with a linear search (no index).
2. Depending on your other constraints, you could write a script that used FEMTO to search for some relatively modest number of possibilities (like "hello") and use --offsets. Then you could parse the offsets and read from the matching files to check the rest of your pattern. Of course, even better if you don't actually need to do things like .{100} - these seem to me to be unlikely to be actually useful in practice. Perhaps explaining more what you are trying to do could help me offer advice. If you do develop such a script - you are welcome to contribute it back to the project. It is open source, after all :)

**Comment by Manoj321** [comment]
Great. Thanks!
I'm currently investigating 
1. [Livegrep](https://github.com/livegrep/livegrep) 
2. Of course FEMTO and
3. [Hyperscan](https://github.com/01org/hyperscan)
If I decide to use FEMTO, I'll definitely contribute to the community in case I develop anything!

**Comment by mppf** [comment]
The below may be obvious to you - I'm just trying to be helpful.

With a cursory look, it's hard for me to tell what livegrep is actually doing... But judging from the docs, Femto is designed for larger indexes. I'd also expect a Femto index to be smaller - usually 1/2 original data for text. Anyway, the other difference is that Femto indexes byte sequences - they could be source code or text or DNA or whatever. It doesn't treat newlines, specially for example.

And it looks to me like hyperscan compiles the regexps but then scans the data - meaning it would offer O(n) search over n bytes of data.

Femto offers constant-time counting for simple non-regexp  patterns (counting - use --count or --matches to ask how many matches to a string occur? ). It's technically O(m) where m is the pattern length, and there might be a log n in there depending on how you analyze it, but anyway it is much less than O(n). Then, if you want a list of documents matched or offsets, there is some per-result cost, but you might only need the first 100 matches (say).

So, if you're willing to index your data (the searched data isn't changing too quickly) Femto may well offer a speed advantage with larger data sets.

I've always thought Femto could make a nice code search tool but it's not something I've had time to try.

I'm curious to know the result of your investigation.

**Comment by Manoj321** [comment]
Just to add to your analysis:

Livegrep basically constructs suffix array of input text data( and some compression) and it uses googles RE2 to do the regex matching. The speed is relatively good but
  Cons:
     - cannot do multiline search.

**Comment by mppf** [comment]
I wanted to mention that it is possible to run a number of queries at once. The program src/main/query_tool does this. You might get better performance by running your queries in batches. You could experiment with query_tool to see if there is benefit in your case but it won't handle regular expressions. I can offer further suggestions if this turns out to look promising.

**Comment by Manoj321** [comment]
Thanks for pointing this out. This is 5x faster than going through each non-regexp. Please keep your suggestions coming :)

**Comment by mppf** [comment]
The search system also supports multithreaded searching with work stealing, but it is disabled by default. Search for the line

    //TEMP - force number of threads to 1.
  settings->num_threads = 1;

In server.c if you want to experiment with it.

Also while query_tool does not support regexps, it would not be hard to write a similar parallel search tool that does.
